---
- name: Deploy to Cluster
  hosts: all
  become: true
tasks:
  - name: Deploy Pod
    shell: |
      kubectl apply -f pod.yml
  
  - name: Deploy Service
    shell: | 
      kubectl apply -f service.yml