apiVersion: v1
kind: Deployment
metadata:
  name: sopa
  labels:
    app: sopa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sopa
  containers:
    - name: sopa
      image: sopa/megadados_aps1
      ports:
        - containerPort: 80